#!/usr/bin/env python3
"""Generate the data behind chrome://aerium from the patch series themselves.

The point of the page is that a user can see exactly what this build changes on
top of upstream Chromium. That is only trustworthy if the list cannot drift from
what was actually applied, so it is derived from the same series files
apply_patches() feeds to utils/patches.py - never hand-maintained.

Emits a C++ initialiser list to a .inc, textually included by the WebUI. A .inc
rather than a generated .cc keeps it out of BUILD.gn: the build already fails
loudly if this script did not run, because the include goes missing.
"""

import argparse
import os
import sys

# Series path prefix -> the heading it appears under. Longest match wins, so
# the more specific core/extra entries beat the bare project names.
_GROUPS = [
    ('aerium-fatih/', 'Aerium'),
    ('ungoogled-fatih/', 'Aerium'),
    ('upstream-fixes/', 'Upstream fixes'),
    ('core/ungoogled-chromium/', 'Ungoogled Chromium'),
    ('extra/ungoogled-chromium/', 'Ungoogled Chromium (optional)'),
    ('core/bromite/', 'Bromite'),
    ('extra/bromite/', 'Bromite (optional)'),
    ('core/inox-patchset/', 'Inox patchset'),
    ('extra/inox-patchset/', 'Inox patchset (optional)'),
    ('core/iridium-browser/', 'Iridium'),
    ('extra/iridium-browser/', 'Iridium (optional)'),
    ('core/debian/', 'Debian'),
    ('extra/debian/', 'Debian (optional)'),
    ('ungoogled-chromium/portablelinux/', 'Portable Linux packaging'),
    ('ungoogled-chromium/windows/', 'Windows packaging'),
]


def group_for(rel):
    best = ''
    label = 'Other'
    for prefix, name in _GROUPS:
        if rel.startswith(prefix) and len(prefix) > len(best):
            best, label = prefix, name
    return label


def describe(path):
    """First paragraph of prose above the first diff header, if there is one.

    Three shapes occur in practice: plain prose (Aerium's own patches),
    '#'-prefixed comments (some ungoogled patches), and nothing at all. Returns
    ('', 0) when there is no description, so the caller can fall back rather
    than inventing one.
    """
    lines = []
    files = 0
    try:
        with open(path, 'r', errors='replace') as fh:
            for line in fh:
                if line.startswith('--- a/') or line.startswith('--- /dev/null'):
                    break
                if line.startswith('diff ') or line.startswith('+++ '):
                    break
                lines.append(line.rstrip('\n'))
        with open(path, 'r', errors='replace') as fh:
            for line in fh:
                if line.startswith('+++ b/'):
                    files += 1
    except OSError:
        return '', 0

    para = []
    for raw in lines:
        s = raw.lstrip('#').strip() if raw.lstrip().startswith('#') else raw.strip()
        if not s:
            if para:
                break
            continue
        para.append(s)
    return ' '.join(para), files


def humanise(rel):
    stem = os.path.basename(rel)
    for suffix in ('.patch', '.diff'):
        if stem.endswith(suffix):
            stem = stem[:-len(suffix)]
    stem = stem.replace('-', ' ').replace('_', ' ').strip()
    return stem[:1].upper() + stem[1:] if stem else rel


def cpp_escape(s):
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append(' ')
        elif ord(ch) < 0x20:
            out.append(' ')
        else:
            out.append(ch)
    return ''.join(out)


def collect(series_path, patch_root):
    entries = []
    if not os.path.isfile(series_path):
        return entries
    with open(series_path, 'r', errors='replace') as fh:
        for line in fh:
            rel = line.strip()
            if not rel or rel.startswith('#'):
                continue
            full = os.path.join(patch_root, rel)
            summary, files = describe(full)
            if not summary:
                summary = humanise(rel)
            entries.append((group_for(rel), os.path.basename(rel), summary, files))
    return entries


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--series', action='append', nargs=2, metavar=('SERIES', 'ROOT'),
                    required=True,
                    help='a series file and the directory its entries are relative to')
    ap.add_argument('--chromium-version', default='')
    ap.add_argument('-o', '--output', default='-')
    args = ap.parse_args()

    entries = []
    for series, root in args.series:
        entries.extend(collect(series, root))

    out = []
    out.append('// Generated by scripts/generate_patch_manifest.py - do not edit.')
    out.append('// Regenerated on every build from the patch series, so it cannot')
    out.append('// disagree with what was actually applied.')
    out.append('')
    out.append('constexpr char kAeriumChromiumVersion[] = "%s";' %
               cpp_escape(args.chromium_version))
    out.append('')
    out.append('constexpr AeriumPatchEntry kAeriumPatches[] = {')
    for group, name, summary, files in entries:
        out.append('    {"%s", "%s", "%s", %d},' %
                   (cpp_escape(group), cpp_escape(name), cpp_escape(summary), files))
    out.append('};')
    out.append('')

    text = '\n'.join(out) + '\n'
    if args.output == '-':
        sys.stdout.write(text)
    else:
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, 'w') as fh:
            fh.write(text)
        sys.stderr.write('[aerium] wrote %d patch entries to %s\n'
                         % (len(entries), args.output))


if __name__ == '__main__':
    main()
